Algoritmo "media"
var
   n1,n2,n3,p1,p2,p3,media:real
inicio
      escreva ("digite a primeira nota:")
      leia (n1)
      escreva ("peso da primeira nota:")
      leia (p1)
      escreva ("digite a segunda nota:")
      leia (n2)
      escreva ("peso da segunda nota:")
      leia (p2)
      escreva ("digite a terceira nota:")
      leia (n3)
      escreva ("peso da terceira nota:")
      leia (p3)
media<- (n1*p1+n2*p2+n3*p3)/(p1+p2+p3)
escreval ("media=",media)
fimalgoritmo
